package com.hermes.mobile.ui

import com.hermes.mobile.models.Artifact
import com.hermes.mobile.models.ArtifactKind
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlinx.coroutines.test.runTest
import kotlinx.datetime.Instant

class ArtifactsLoaderTest {
    @Test
    fun loadsArtifactsFromGateway() = runTest {
        val loader = ArtifactsLoader(FakeArtifactsGateway())

        val state = loader.load()

        assertIs<ArtifactsLoadState.Ready>(state)
        assertFalse(state.usingFallback)
        assertEquals(2, state.artifacts.size)
        assertEquals("mobile-api.patch", state.artifacts.first().title)
        assertEquals(ArtifactKind.File, state.artifacts.first().kind)
    }

    @Test
    fun returnsOfflineFallbackWhenGatewayFails() = runTest {
        val loader = ArtifactsLoader(FailingArtifactsGateway())

        val state = loader.load()

        assertIs<ArtifactsLoadState.Ready>(state)
        assertEquals(true, state.usingFallback)
        assertEquals("Gateway unavailable · showing sample artifacts", state.notice)
        assertEquals("Sample artifact", state.artifacts.first().title)
    }
}

private class FakeArtifactsGateway : ArtifactsGateway {
    override suspend fun artifacts(): List<Artifact> = listOf(
        Artifact(
            id = "art_patch",
            sessionId = "sess_recent",
            kind = ArtifactKind.File,
            title = "mobile-api.patch",
            summary = "Patch generated by Hermes.",
            mimeType = "text/x-diff",
            uri = "file:///tmp/mobile-api.patch",
            sizeBytes = 1024,
            metadata = mapOf("language" to "diff"),
            createdAt = Instant.parse("2026-06-24T10:00:00Z"),
        ),
        Artifact(
            id = "art_log",
            sessionId = "sess_recent",
            kind = ArtifactKind.Log,
            title = "smoke.log",
            summary = "Smoke test output.",
            createdAt = Instant.parse("2026-06-24T10:01:00Z"),
        ),
    )
}

private class FailingArtifactsGateway : ArtifactsGateway {
    override suspend fun artifacts(): List<Artifact> = error("offline")
}
